### ISSUE TITLE
Cannot access Google Drive with Arc browser

### ISSUE THREAD

**Issue by pasiooooo** [sapjax/word-hunter#11]
Arc browser: https://arc.net/

Google Drive give me this warning: 

> You can’t sign in because Word Hunter sent an invalid request. You can try again later, or contact the developer about this issue. Learn more about this error
> If you are a developer of Word Hunter, see error details.
> Error 400: invalid_request

P.S. It worked in Chrome.

**Comment by sapjax** [comment]
This problem is caused by the ARC browser not supporting `chrome.identity.getAuthToken` and always using `chrome.identity.launchWebAuthFlow` to process the auth flow, I can use `launchWebAuthFlow` to make it work, but now I haven't find a way to distinguish Chrome and ARC yet.

**Comment by pasiooooo** [comment]
Thank you for your reply, your work is excellent. 

Looking forward to the problem being resolved later.

**Comment by sapjax** [comment]
It seems Arc has no plan to fix this issue, just close now.
