### ISSUE TITLE
An error occurred on the website pop-up windows

### ISSUE THREAD

**Issue by pasiooooo** [sapjax/word-hunter#13]
Website URL: https://learngitbranching.js.org/?locale=en_US

![CleanShot 2023-10-18 at 09 10 17](https://github.com/sapjax/word-hunter/assets/45416227/642af62d-bed3-4e85-b0e6-81e9359ee54c)

- Unable to mark words, pop-up windows will quickly disappear.
- Zen-mode does not work

P.S. Chrome has the same problem.

**Comment by sapjax** [comment]
@pasiooooo 
The website's code added the [inert](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) to all other elements on the page, 
This is the intention of the website author, to disable the click event on other elements, to make sure the website's features work as expected.

So this is not a bug, and no need to fix it. It is best to follow the website author's idea.
for our extension, you can press the `a` key to mark a word as known when the card is open.

**Comment by pasiooooo** [comment]
Thanks for the tips.
