### ISSUE TITLE
Feature request: When the word is marked as known, the Chinese translation disappears with it.

### ISSUE THREAD

**Issue by pasiooooo** [sapjax/word-hunter#17]
Now:

`This is a ==test==(测试).`--[mark]-->`This is a test(测试).`

Expectation:

`This is a ==test==(测试).`--[mark]-->`This is a test.`

**Comment by sapjax** [comment]
@pasiooooo 
This is by design, See https://github.com/sapjax/word-hunter/issues/8

**Comment by sapjax** [comment]
@pasiooooo 
This is by design, See https://github.com/sapjax/word-hunter/issues/8
