### ISSUE TITLE
Can you add translation to the dictionary

### ISSUE THREAD

**Issue by edisonyan** [sapjax/word-hunter#2]
Thank you very much for developing the addon . I would like to make some suggestions. For non-native English speakers like me, we need translations and explanations for unknown words even more. English explanations are still difficult for me to understand. Could you add a feature to the dictionary to translate words into corresponding languages (e.g. Chinese)?

**Comment by maxzhang666** [comment]
建议可以增加翻译功能

还有翻译引擎的选择功能

比如国产的翻译引擎让用户自己提供AppKey之类的东西也是很棒的

**Comment by sapjax** [comment]
> 建议可以增加翻译功能
> 
> 还有翻译引擎的选择功能
> 
> 比如国产的翻译引擎让用户自己提供AppKey之类的东西也是很棒的

[immersivetranslate](https://immersivetranslate.com/) 应该就是你需要的，这两个扩展并不冲突，可以一起使用

**Comment by maxzhang666** [comment]
> > 建议可以增加翻译功能
> > 还有翻译引擎的选择功能
> > 比如国产的翻译引擎让用户自己提供AppKey之类的东西也是很棒的
> 
> [immersivetranslate](https://immersivetranslate.com/) 应该就是你需要的，这两个扩展并不冲突，可以一起使用

建议而已、

在用Relingo了、、

**Comment by sapjax** [comment]
v1.0.22 添加了选项，可以在常见单词后面显示中文翻译
