### ISSUE TITLE
FR: add option for to setting the interval when pop-ups automatically disappear

### ISSUE THREAD

**Issue by pasiooooo** [sapjax/word-hunter#20]
The current default disappearance interval of the pop-up window is a bit slow for me personally, causing reading resistance.

Therefore, I expect to be able to control it myself.

**Comment by sapjax** [comment]
I guess you mean the delay of hiding when the mouse leaves?
currently, you can click outside of the window to close it immediately.

If you mean the hiding animation duration, you can set `Reduce motion` in the OS's System accessibility settings.

**Comment by pasiooooo** [comment]
> I guess you mean the delay of hiding when the mouse leaves?

Yes, it's this.
