### ISSUE TITLE
FR: automatically hide Chinese translation for the content in the code blocks

### ISSUE THREAD

**Issue by pasiooooo** [sapjax/word-hunter#21]
1. Usually, the code does not need translation assistance.
2. The Chinese translation will be copied if using the copy button of code blocks, although it will not be selected.

test url: https://forum.obsidian.md/t/dataview-plugin-snippet-showcase/13673

![CleanShot 2023-11-06 at 14 58 28](https://github.com/sapjax/word-hunter/assets/45416227/f660125d-dc01-4c5f-b005-538b929f044d)

**Comment by sapjax** [comment]
It will cause bad performance if we check whether every text has a `code` ancestor or not.
so I just hide the translation in these situations.
BTW: this fix should be released in version v1.1.4, not v1.1.3, the v1.1.3 is in audit and will be published automatically after audit.
