### ISSUE TITLE
Feature request: a option or a switcher to handle whether show Chinese translation in all website.

### ISSUE THREAD

**Issue by liserjrqlxue** [sapjax/word-hunter#22]
有时，当我不想在页面上看到中文翻译时，当我只能通过 关闭 "Enable on this site" 开关来停止插件在此页面上的工作，然后刷新页面。如果页面太多，只能停止插件，然而停止/启用插件也不是很方便。
如果有一个类似 "在本网站启用 "的选项（全局）或开关，那就方便多了。

------------------------------------------------------------------------------------------------------------------

Sometimes, when I don't want to see Chinese translation on the page, I can only stop the plugin working on this page by swith "Enable on this site" to close and then refresh the page. 
If there are too many pages, I can only stop the plugin, while it is not very convenient to stop/enable the plugin.
It would be much more convenient if there was an option (global) or switcher like "Enable on this site".

**Comment by sapjax** [comment]
@liserjrqlxue 

<img width="330" alt="image" src="https://github.com/sapjax/word-hunter/assets/990255/62e890aa-c2a5-4131-a9f3-5351b26635b4">

There is a switcher in options.
