### ISSUE TITLE
"Mark As Unknown" in Context Menu don't working

### ISSUE THREAD

**Issue by becauseim** [sapjax/word-hunter#23]
word is not highlighted after the action:

<img width="603" alt="Screenshot 2023-11-25 at 03 36 58" src="https://github.com/sapjax/word-hunter/assets/23287366/e2105473-19a6-44a8-bed4-6f6008642e30">

**Comment by sapjax** [comment]
> word is not highlighted after the action:

The word `percussive` is not in the built-in [word list](https://raw.githubusercontent.com/sapjax/word-hunter/main/public/eng-dict.txt), it is not considered a word. 
currently, it doesn't support marking an arbitrary word as unknown, the word must be already in the word list.

**Comment by becauseim** [comment]
> > word is not highlighted after the action:
> 
> The word `percussive` is not in the built-in [word list](https://raw.githubusercontent.com/sapjax/word-hunter/main/public/eng-dict.txt), it is not considered a word. currently, it doesn't support marking an arbitrary word as unknown, the word must be already in the word list.

The action "Mark As Unknow" does not work with any word. I tried different words, including built-in word list (welcome, safe..).

**Comment by sapjax** [comment]
> The action "Mark As Unknow" does not work with any word. I tried different words, including built-in word list (welcome, safe..).

Can you check the **Levels** setting in the options page, I think they are already `unknown` but within the unselected level.

If this is the case, the logic is right, but the interaction is a little bit confusing and needs to be optimized.

**Comment by sapjax** [comment]
> Please update the logic by prioritizing manually unknown word even it is in unselected level. Please reopen this issue.

It's already set as **unknown**, but because it is in the unselected level it will not be highlighted, if you want it to show, you can change the levels setting in the options page.
the "Mark As Unknow" feature is not for mark words, it's only for Undo the wrong "Mark as known".
<img width="320" alt="image" src="https://github.com/sapjax/word-hunter/assets/990255/4f435ca8-59df-4e45-88d5-53ec1a061c97">

**Comment by CEX68** [comment]
> > Please update the logic by prioritizing manually unknown word even it is in unselected level. Please reopen this issue.
> 
> It's already set as **unknown**, but because it is in the unselected level it will not be highlighted(最有意思), if you want it to show, you can change the levels setting in the options page. the "Mark As Unknow" feature is not for mark words, it's only for Undo the wrong "Mark as known". <img alt="image" width="320" src="https://private-user-images.githubusercontent.com/990255/287492914-4f435ca8-59df-4e45-88d5-53ec1a061c97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzA0MTUsIm5iZiI6MTcwMTU3MDExNSwicGF0aCI6Ii85OTAyNTUvMjg3NDkyOTE0LTRmNDM1Y2E4LTU5ZGYtNGU0NS04OGQ1LTUzZWMxYTA2MWM5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMjIxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTFjOGQwYjdiMjc0NTA1MTIwMWQ4Nzk0NzZhNGFlZTdkYTUxODUwODIxN2Q3NzMxMzkyOTFlNGIzNDhmMTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wxut73ckQN4Og7AKTl5oCKprgJvEtCvQB0_C9hPczJA">

I understand this logic but it is not efficient. Someone may be unfamiliar with 100 words of CET-4 which has 4500 words, he needs to mark 4400 words as known in your logic but 100 words in my logic above.

**Comment by sapjax** [comment]
> I understand this logic but it is not efficient. Someone may be unfamiliar with 100 words of CET-4 which has 4500 words, he needs to mark 4400 words as known in your logic but 100 words in my logic above.

Sure, you are right, but according to the `chrome.sync` storage limit, we only store the state `known` or `unknown` in one byte,  no extra information, so I can't implement the logic you expected.
for me, I selected all the levels, and mark all the words manually, the `level` system does not suit me.

**Comment by CEX68** [comment]
> > I understand this logic but it is not efficient. Someone may be unfamiliar with 100 words of CET-4 which has 4500 words, he needs to mark 4400 words as known in your logic but 100 words in my logic above.
> 
> Sure, you are right, but according to the `chrome.sync` storage limit, we only store the state `known` or `unknown` in one byte(字节), no extra information, so I can't implement(工具) the logic you expected. for me, I selected all the levels, and mark all the words manually, the `level` system does not suit me.

Add a `forceTrans` can achieve my logic.

```
function _makeAsUnknown(word: string) {
  delete wordsKnown[word]
  highlight(document.body, true)
}
function highlight(node: Node, word?: string, forceTrans?: bool) {
  const textNodes = getTextNodes(node)
  for (const node of textNodes) {
    highlightTextNode(node, dict, wordsKnown, word, forceTrans)
  }
}

function highlightTextNode(node: CharacterData, dict: WordInfoMap, wordsKnown: WordMap, word?: string, forceTrans?: bool) {
    if (!(originFormWord in wordsKnown) || forceTrans)
}
```

I am sorry I can't submit a PR because I don't know how to write TS and develop Chrome extension.

**Comment by betgo** [comment]
> @CEX68 It's more complicated than the code above, the problem is not to highlight words, it's about storage, we can't set a `known` word as `known`, that's no effect, we should keep the info in storage **A word is known, but manually set it to known again**
> 
> I can implement it, but it will make the code a little bit tricky, I think it's a product problem, not a code problem, before we find a better way to do that, we should not make any changes.

Can we create a new array to store users' unknown words? For me, it is enough to highlight unknown words.Becouse we can translate it by ohter way.
