### ISSUE TITLE
对于同时使用mac和win的chrome用户，设置快捷键会相互覆盖，能否针对不同系统提供不同快捷键的设置？

### ISSUE THREAD

**Issue by GoTop** [sapjax/word-hunter#30]
win系统里没有花键，mac系统里没有ctrl

但是快捷键设置会互相同步覆盖，导致每次换系统都要重新设置快捷键

**Comment by sapjax** [comment]
@GoTop 

I think the `⌘ Command` key in Windows is the `Win` key,
On Mac there is a `Ctrl` key actually.
or you can set the **Modifier Keys** to make them work consistently.
<img width="782" alt="image" src="https://github.com/sapjax/word-hunter/assets/990255/07d47dd5-75b3-40b3-97a8-b47895a4d17d">

**Comment by GoTop** [comment]
在mac中，为了符合win键盘的习惯，我已经将command键设置为Ctrl键

我想插件实现的功能是，可以将快捷键的设置分成两个部分，可以分别设置在win、mac系统中使用不同的快捷键
