### ISSUE TITLE
选择GRE8000以上难度，但是还是有很多很简单的单词会被标注为unkown

### ISSUE THREAD

**Issue by GoTop** [sapjax/word-hunter#31]
只勾选了无限符号的那个，其他难度的全部未选，但是还是有很多很简单的单词会被标注为unkown

**Comment by sapjax** [comment]
> 只勾选了无限符号的那个，其他难度的全部未选，但是还是有很多很简单的单词会被标注为unkown

Although most users of this project are Chinese users, there are still users in other languages. To avoid submitting issues repeatedly, please submit issues in English.

The levels are grouped by https://github.com/mahavivo/english-wordlists, it's not really `level`, just a collection of words, some words may be in that level, but not in the collection.

I plan to remove the level system in the future and change to the `word frequency` system, users can select the percentage of frequency to choose what words should be highlighted.
