### ISSUE TITLE
It is recommended that the pop-up translation window be small to simplify the display information

### ISSUE THREAD

**Issue by milkday** [sapjax/word-hunter#32]
Pop-ups are too large to block the page information, affecting the experience. The content inside can also be streamlined, try to show a few necessary translations, too many sentences and explanations most people will not read.

**Comment by sapjax** [comment]
> Pop-ups are too large to block the page information, affecting the experience. The content inside can also be streamlined, try to show a few necessary translations, too many sentences and explanations most people will not read.

This is too subjective, and everyone has different feelings. from my point of view, I think it's OK.

**Comment by sapjax** [comment]
reduce some contents of collins in https://github.com/sapjax/word-hunter/commit/0e73f56b0dc103ae31771af5420f15c2eb3be063 , will be released in the next version.
