### ISSUE TITLE
Query multiple unknown words in same context through OpenAI

### ISSUE THREAD

**Issue by CEX68** [sapjax/word-hunter#33]
Word Hunter queries only when the mouse is hovering. You may need to move the mouse several times when encountering multiple unknown words in the same context. I specifically request this feature exclusively for OpenAI, as it can query multiple words in the same context, unlike other dictionaries.

**Comment by sapjax** [comment]
> Word Hunter queries only when the mouse is hovering. You may need to move the mouse several times when encountering multiple unknown words in the same context. I specifically request this feature exclusively(排他地) for OpenAI, as it can query multiple words in the same context, unlike other dictionaries.

This case is rare, no plan to implement it yet.

You can customize the `prompt` of OpenAI in settings to:

```
Explain the word ${word} in the sentence ${context}, also explain other words above B1+ in this sentence, in simple English.
```
