### ISSUE TITLE
Enable automatic syncing for Google Drive

### ISSUE THREAD

**Issue by CEX68** [sapjax/word-hunter#34]
Google Drive only syncs after clicking the button, please enable automatic syncing.

**Comment by sapjax** [comment]
> Google Drive only syncs after clicking the button, please enable automatic syncing.

It automatically syncs after you mark a word or save a context, or start up Chrome.
There is a one-minute delay after these operations.

If it does not sync automatically, often because the auth token is expired, you should see an error icon ❌ above the extension icon, at that time, you should trigger a manual sync by click the sync button.

**Comment by CEX68** [comment]
> > Google Drive only syncs after clicking the button, please enable automatic syncing.
> 
> It automatically syncs after you mark a word or save a context, or start up Chrome. There is a one-minute delay after these operations.
> 
> If it does not sync automatically, often because the auth token is expired, you should see an error icon ❌ above the extension icon, at that time, you should trigger(扳机) a manual sync by click the sync button.

I clicked on Google Sync 12 hours ago(assuming the auth token is not expired) and marked a word as known just now, but it didn't sync automatically, the `word_hunter_backup.json` was modified 12 hours ago in Google drive. I also didn't notice any network activity or errors in the Chrome console when I marked a word as known.

**Comment by sapjax** [comment]
> I clicked on Google Sync 12 hours ago, so the auth token was not expired until now. I marked a word as known just now, but it didn't sync automatically, the `word_hunter_backup.json` was still modified 12 hours ago in Google drive. I also didn't notice any network activity or errors in the Chrome console when I marked a word as known.

@CEX68  
check the file version history in Google drive, not the directory.
The network activity is in background service worker script, not in the context script
<img width="425" alt="image" src="https://github.com/sapjax/word-hunter/assets/990255/9ecd17f0-1cea-45a6-8c64-42d362457263">

**Comment by CEX68** [comment]
> > I clicked on Google Sync 12 hours ago, so the auth token was not expired until now. I marked a word as known just now, but it didn't sync automatically, the `word_hunter_backup.json` was still modified 12 hours ago in Google drive. I also didn't notice any network activity or errors in the Chrome console(安慰) when I marked a word as known.
> 
> @CEX68 check the file version history in Google drive, not the directory. The network activity is in background service worker script, not in the context script <img alt="image" width="425" src="https://private-user-images.githubusercontent.com/990255/291022213-9ecd17f0-1cea-45a6-8c64-42d362457263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3ODUyMTEsIm5iZiI6MTcwMjc4NDkxMSwicGF0aCI6Ii85OTAyNTUvMjkxMDIyMjEzLTllY2QxN2YwLTFjZWEtNDVhNi04YzY0LTQyZDM2MjQ1NzI2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwMzQ4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTdhODUxYmNkOTBkOThjNjcwZWMzOWI2N2M4NDE3NjA4OTI3MWE3ZTU5OGJjYTJkMTYyMzczZTA2ZDVlMWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rghvw6BUap4LX5hRthfpFQ6K3sZ2YZVFamGSKxFjSHA">

What I mentioned is file. The word hunter version is 1.1.5, the same as yours.

**Comment by sapjax** [comment]
@CEX68 
You can enable the `Developer mode` on chrome://extensions/ page,
then click the **service worker** link on Word Hunter extension to view the network activity or error message in the console to find what happend.
