### ISSUE TITLE
Add a blacklist function to disable word hunter on specified websites

### ISSUE THREAD

**Issue by CEX68** [sapjax/word-hunter#37]
Word hunter may cause disruptions when input Chinese so I want to disable it on specified websites.

**Comment by sapjax** [comment]
> Word hunter may cause disruptions when input Chinese so I want to disable it on specified websites.

Click the word-hunter icon, there is a button in the popup window.
<img width="261" alt="image" src="https://github.com/sapjax/word-hunter/assets/990255/9bfd1a1c-ef03-46e8-810b-d899c7e06a9c">
