### ISSUE TITLE
Not compatible with other translation extension when showing Chinese translation

### ISSUE THREAD

**Issue by pasiooooo** [sapjax/word-hunter#38]
Chinese translation will be mixed into the translation such as Immersive Translate.

![CleanShot 2024-01-08 at 15 52 55@2x](https://github.com/sapjax/word-hunter/assets/45416227/38e36197-ab41-4c65-8b3d-13490d97bcd5)

**Comment by sapjax** [comment]
@pasiooooo 
This is not a problem for either, the translation of word-hunter is in the text, so the Immersive Translate just translates it.

You can go to the **developer settings** page of Immersive-Translate
and paste this code into the **Edit user rules** textarea:
```
[
  {
    "matches": "*",
    "excludeSelectors": [
      "w-mark-t"
    ]
  }
]
```
then the Immersive-Translate will ignore the Chinese translation of word-hunter.

**Comment by pasiooooo** [comment]
Very helpful, thank you very much.

**Comment by corwin1949** [comment]
The above code may cause some websites, such as X.com, to display translations incorrectly. If you encounter the same issue, you can change it to the following rule.

```
[
  {
    "generalRule": {
      "excludeSelectors.add": [
        ".word_card",
        ".footer"
      ]
    }
  }
]

Avoid the following error displays
![image](https://github.com/user-attachments/assets/3de4b2f3-bfd0-4900-9340-78c0b1810d98)
