### ISSUE TITLE
Add shortcut for marking as known

### ISSUE THREAD

**Issue by zimonitrome** [sapjax/word-hunter#4]
Would be nice to have a keyboard shortcut that marks a word as "known" without having to press the check icon button.

**Comment by sapjax** [comment]
I’m using [Vimium](https://chrome.google.com/webstore/detail/dbepggeogbaibhgnhhndojpepiihcmeb) to do it.
<img width="582" alt="image" src="https://github.com/sapjax/word-hunter/assets/990255/344b3b16-3b21-420d-96b8-04acd45ef1e8">

when the dictionary window is opened, press `f` to enter hint mode, then you can press the key on the known button.
and you even can press the key above the word to show the dictionary window.

**Comment by sapjax** [comment]
I released a new version  1.0.24.
still add two shortcut keys:
- `a` for mark as known
- `s` for save context
