### ISSUE TITLE
Change volume

### ISSUE THREAD

**Issue by zimonitrome** [sapjax/word-hunter#5]
Would be nice to be able to set the volume of pronounced words. It's a little too loud for me at the moment.

**Comment by sapjax** [comment]
> Would be nice to be able to set the volume of pronounced words. It's a little too loud for me at the moment.

Sounds reasonable, will add it in the next version.

**Comment by sapjax** [comment]
Add an option in version 1.0.24.

<img width="528" alt="image" src="https://github.com/sapjax/word-hunter/assets/990255/b7e251a8-ade5-4128-aeae-a1f2b361fb7b">
