### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by chicager** [sapjax/word-hunter#6]
Hi! I'm the guy from the reviews section in the Chrome Store)
I found your extension very useful, Zen mode is a very cool feature!
I use it as of my database of words that I know, i.e. first I made all the words are unknown via selecting all the dics for highlighting and started adding words that I know.
I would like to suggest a few improvements:
1. As I wrote in the reviews, pls add the ability to manually make a word to unknown.
2. In Chrome-based mobile browsers with extension support (I use Mask Browser on Android), the extension does not work correctly :((, it's just a huge disappointment, could you pls fix it? It's a critical functionality to be able use it across devices.
3. When you hover the mouse over a word and a pop-up window appears and if there are a lot of words on the page, then the pop-up window may appear on another word and it can be accidentally added to the database, and you have to export the database and delete the wrong word manually, this is very inconvenient, it would be cool to add a history of adding words so that you can quickly undo addition.
4. It would be cool to be able to highlight not only words, but also stable phrases and phrasal verbs, so as not to confuse them, there can be a separate list for them and they can be highlighted with the different color.
5. It would be cool to be able not to distinguish words in the singular and plural like dog and dogs.
6. To have the ability in the pop-up window see the translation into a target language and not just see the definition in the dics.
7. To have the ability to invert all the words in the Zen mode.
8. Could you pls add synchronization for example via Google Drive? I saw it in the settings, but I didn't understand how it works.

**Comment by sapjax** [comment]
@chicager 

Thanks for your thoughtful suggestions:
1. it's in plan.
2. I didn't even know Chrome-based mobile browsers can support extensions, I'll check it later.
3. yeah, I saw the feature in [word-discoverer](https://github.com/mechatroner/word-discoverer), just didn't know how often people use it, now I think it would be better to implement it.
4. the feature of phrases is a little bit complicated to implement, cause there are too many phrases but we can only choose a part of them, and it might need to change a lot of code, will evaluate it after other features are done. 
5. actually I already handled the plural and tense, for example, if you mark the word **woodpecker** as known, it will automatically mark **woodpeckers** as known, and vice versa.
this feature depends on the built-in pre-paired words list in code, for some words, the plural or tense may be wrong, This is hard to avoid and needs to be revised slowly.
6. I guess you mean the translation of the context? this extension is not intended to be a translation app, and it's hard to support all target languages, I have the plan to provide the ability to allow users to add a dict tab in the window, and users can input the request URL with the variable `${word}` and `${context}`, for example, you can use https://translate.google.com/?sl=auto&tl=ja&text=${word}&op=translate to translate the word to Japanese via google translate.
7. it's easy, will support it.
8. right now, the extension automatically syncs via Google extension's storage between different Chrome browsers, you do not need to do anything, but this feature has not been tested extensively, may have a bug,  and according to the sync limit size of Chrome, it not include the context data, I may add the support of Google Drive when I remove the manually **backup** and **restore**.

**Comment by chicager** [comment]
@sapjax 

Thanks for your reply!

A few clarifications:

2. Pls check it, it'd be really great to have the ability to use the extension across devices!
4. You don't have to use the dic for the for phrasal verbs and phrases. If it will be possible to manually add words as unknown, we can simply check if the user has selected several words at once and is trying to add them, then add them to the list with phrases and simply highlight them in a different color.
5. It doesn't work, you can check it with this for example: pastebin.com/fLSYkuz0
6. Yes, I meant as you described  just a dict tab in the window with the words as variables in the link for translation.
8. It seems to me that it is better not to remove the ability to manually import and export the database, because some may have problems setting up Google Drive and this will remain their only backup option.

**Comment by sapjax** [comment]
> @sapjax
> 
> Thanks for your reply!
> 
> A few clarifications:
> 
> (2) Pls check it, it'd be really great to have the ability to use the extension across devices! (4) You don't have to use the embedded dic for the for phrasal verbs and phrases. If it will be possible to manually add words as unknown, we can simply check if the user has selected several words at once and is trying to add them as unknown, then add them to the list with phrases and simply highlight them in a different color. (5) It doesn't work, you can check it with this for example: pastebin.com/fLSYkuz0 (6) Yes, I meant as you described just a dict tab in the window with the words as variables in the link for translation. (8) It seems to me that it is better not to remove the ability to manually import and export the database, because some may have problems setting up Google Drive and this will remain their only backup option.

(2) yeah, I already fixed the problem in Mask Browser, just didn't publish it yet, cause it's not the official Chrome browser, the data does not sync between your Chrome with Mask Browser, so it might not be across devices as you expected.

(4) OK, but if no embedded phrasal verbs, how can users know what the phrasal verbs are? if they know the phrasal verbs, maybe they are already familiar with them.

(5) which version are you using, the example works for me, I think it should be no problem after v1.0.22.

(8) You're right, some people also need a VPN to access Google service.

**Comment by chicager** [comment]
> > @sapjax
> > Thanks for your reply!
> > A few clarifications:
> > (2) Pls check it, it'd be really great to have the ability to use the extension across devices! (4) You don't have to use the embedded dic for the for phrasal verbs and phrases. If it will be possible to manually add words as unknown, we can simply check if the user has selected several words at once and is trying to add them as unknown, then add them to the list with phrases and simply highlight them in a different color. (5) It doesn't work, you can check it with this for example: pastebin.com/fLSYkuz0 (6) Yes, I meant as you described just a dict tab in the window with the words as variables in the link for translation. (8) It seems to me that it is better not to remove the ability to manually import and export the database, because some may have problems setting up Google Drive and this will remain their only backup option.
> 
> (2) yeah, I already fixed the problem in Mask Browser, just didn't publish it yet, cause it's not the official Chrome browser, the data does not sync between your Chrome with Mask Browser, so it might not be across devices as you expected.
> 
> (4) OK, but if no embedded phrasal verbs, how can users know what the phrasal verbs are? if they know the phrasal verbs, maybe they are already familiar with them.
> 
> (5) which version are you using, the example works for me, I think it should be no problem after v1.0.22.
> 
> (8) You're right, some people also need a VPN to access Google service.

(2) That's bad, can it be synced with Google Drive or that option is also closed?
(4) You're right, I didn't think of that, it can't be implemented without an inbuilt dic. 
(5) v1.0.24 . That's strange

**Comment by sapjax** [comment]
@chicager 

(2) Google Drive should work fine, I'm implementing it.
(5) indeed, that's a bug about highlights, already fixed it, and will release it with other features.

**Comment by chicager** [comment]
@sapjax

Thanks mate!
Waiting for the new release.

**Comment by sapjax** [comment]
@chicager 
The new release has already been published, see [releases/tag/1.0.25](https://github.com/sapjax/word-hunter/releases/tag/1.0.25)
the OAuth login to the app is currently in the verifier process by Google Team.
If you can't do Google Drive authentication, you should wait for the verifier work done.

about features in the origin list:

1. Currently, manually mark a word unknown only for the word builtIn.
2. Fixed
3. For the reason in 1 above ⬆, I didn't implement the history feature, if marked a word as known wrong, you can reset it to unknown by the context menu.
4. No support yet.
5. Fixed
6. No support yet. but you can set the prompt of OpenAI now, so you can use OpenAI as a translator, like: `explain the word ${word} in the sentence "${context}" in Japanese`
7. Added an unselect-all button
8. implemented

**Comment by chicager** [comment]
@sapjax

Thank you! 

Already testing it. Found a bug in the zen mode - the words overlaps each other.
![words](https://github.com/sapjax/word-hunter/assets/10937859/1b3d2d0f-e105-4358-b978-5bf221549eb8)

And those were really bad news about syncro. What a pity. Critical feature. :(

Could you pls explain how the Unselect All button works and in what cases its use is impiled? I didn't understand it at first glance, I meant a bit different saying about inverting.

**Comment by sapjax** [comment]
> @sapjax
> 
> Thank you!
> 
> Already testing it. Found a bug in the zen mode - the words overlaps each other. ![words](https://user-images.githubusercontent.com/10937859/270567312-1b3d2d0f-e105-4358-b978-5bf221549eb8.png)
> 
> And those were really bad news about syncro. What a pity. Critical feature. :(

Thanks!

Just submitted another new release which fixed the style issue.
and I added a textarea to input the Google auth token,  so you can copy the auth token from the Desktop browser to the mobile browser, the steps are:
1. set up the Google Drive sync on the Desktop Chrome in the settings page.
2. open: chrome://identity-internals/ in Chrome, and copy the Access Token value
3. open the settings page on the mobile side, and paste the Access Token into textarea, then it should work.
<img width="369" alt="image" src="https://github.com/sapjax/word-hunter/assets/990255/23a4008d-f756-4e8f-94c9-f94e04af450f">

The auth flow is still in the verifier process by Google Cloud, if you can't log in on the Desktop side, you can send me your Google email address, and I can add you to the test user list.

BTW: I can't test the new release on mobile until the submission is passed, so not sure if there are other problems.

**Comment by sapjax** [comment]
Update: the new version is passed, I tested it, and it works!🎊

**Comment by chicager** [comment]
@sapjax

Thank you! 
The sync works awesome!
I found an another bug, in the mobile browser the loading of word's explanation takes forever and it can't load the content. This happens in all tabs - collins, longman, google, openai, Contexts

**Comment by sapjax** [comment]
> @sapjax
> 
> Thank you! 
> The sync works awesome!
> I found an another bug, in the mobile browser the loading of word's explanation takes forever and it can't load the content. This happens in all tabs - collins, longman, google, openai, Contexts

I did not found this problem on my mobile browser，not sure what happend， sound like network issue.

**Comment by sapjax** [comment]
I didn't find this problem is because I connected the remote debugger to Desktop Chrome, so the script actually ran in my Desktop Chrome.

But the loading is not **forever**, after starting up the Mask Browser, the first request to the dictionary always takes minutes, and then it works normally, don't know why yet, will find it.

**Comment by chicager** [comment]
Confirm, on another my device it works correctly

**Comment by sapjax** [comment]
> Confirm, on another my device it works correctly

Try v1.0.27, should be fixed.
