### ISSUE TITLE
Chinese kept showing even when turned off

### ISSUE THREAD

**Issue by pwwang** [sapjax/word-hunter#7]
Hi, thanks for developing this cool extension! I like the simplicity of it.

I accidentally turned the Chinese on and then tried to turn it off. However, it only worked when I opened a new tab right after. The Chinese is showing again if I open another tab later or even restart the browser. 

I tried to reopen the whole browse and reinstall the extension but with no luck.

The other issue is that when the database is getting larger - some of the pages get a little stuck (memory issue?).

**Comment by sapjax** [comment]
I think they are the same bug of settings, you can update to the new version 1.0.25, should fixed it.

**Comment by pwwang** [comment]
Thanks, that fixed it.
